project_name: thermal-recorder
dist: dist

release:
  github:
    owner: TheCacophonyProject
    name: thermal-recorder
  name_template: '{{.Tag}}'

builds:
- id: thermal-recorder
  binary: thermal-recorder
  main: ./cmd/thermal-recorder
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
- id: leptond
  binary: leptond
  main: ./cmd/leptond
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
- id: thermal-writer
  binary: thermal-writer
  main: ./cmd/thermal-writer
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}

nfpms:
-
  vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Menno Finlay-Smits <menno@cacophony.org.nz>
  description: Record thermal video footage from FLIR Lepton 3 camera
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "_release/thermal-recorder.service": "/etc/systemd/system/thermal-recorder.service"
    "_release/leptond.service": "/etc/systemd/system/leptond.service"
    "_release/thermal-writer.service": "/etc/systemd/system/thermal-writer.service"
    "set-thermal-recorder-output/set-thermal-recorder-output.service": "/etc/systemd/system/set-thermal-recorder-output.service"
    "set-thermal-recorder-output/set-thermal-recorder-output": "/usr/bin/set-thermal-recorder-output"
    "_release/org.cacophony.thermalrecorder.conf": "/etc/dbus-1/system.d/org.cacophony.thermalrecorder.conf"
    "_release/org.cacophony.leptond.conf": "/etc/dbus-1/system.d/org.cacophony.leptond.conf"
  scripts:
    postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
